package app.bookstore;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@org.springframework.stereotype.Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class Controller {
  @Autowired // This means to get the bean called bookRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private BookRepo bookRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewBook (@RequestParam long myISBN
      , @RequestParam String myTitle) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Book n = new Book();
    n.setISBN(myISBN);
    n.setTitle(myTitle);
    bookRepository.save(n);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Book> getAlls() {
    // This returns a JSON or XML with the users
    return bookRepository.findAll();
  }
}